pub enum BusRoute {
    Bus(u64),
    OutOfService,
}

pub struct BusNotes {
    pub earliest_time: u64,
    pub bus_routes: &'static [BusRoute],
}

use BusRoute::*;

// Substitute with:
// '<,'>s/\(\d\+\),/        Bus(\1),/ge | '<,'>s/x,/        OutOfService,/ge | '<,'>s/,/,\r/g
pub const SAMPLE_DATA: BusNotes = BusNotes {
    earliest_time: 939,
    bus_routes: &[
        Bus(7),
        Bus(13),
        OutOfService,
        OutOfService,
        Bus(59),
        OutOfService,
        Bus(31),
        Bus(19),
    ]
};

pub const REAL_DATA: BusNotes = BusNotes {
    earliest_time: 1008832,
    bus_routes: &[
        Bus(23),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(41),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(449),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(13),
        Bus(19),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(29),
        OutOfService,
        Bus(991),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(37),
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        OutOfService,
        Bus(17),
    ]
};
